// ── DATA ──────────────────────────────────────────────────────────────────────

const standardImageData = {
  1214: { RS: { bench: "RS1214", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1214RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1214", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1214LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1215: { RS: { bench: "RS1215", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1215RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1215", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1215LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1414: { RS: { bench: "RS1414", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1414RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1414", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1414LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1415: { RS: { bench: "RS1415", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1415RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1415", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1415LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1515: { RS: { bench: "RS1515", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1515RS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1515L": { RL: { bench: "RL1515", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1515RL_PERSPECTIVE-VIEW.webp"] }, LL: { bench: "LL1515", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1515LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1419: { RS: { bench: "RS1419", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1419RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1419", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1419LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1420: { RS: { bench: "RS1420", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1420RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1420", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1420LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1519: { RS: { bench: "RS1519", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1519RS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1519L": { RL: { bench: "RL1519", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1519RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1519", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1519LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1520: { RS: { bench: "RS1520", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1520RS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1520L": { RL: { bench: "RL1520", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1520RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1520", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1520LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1522: { RS: { bench: "RS1522", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1522RS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1522L": { RL: { bench: "RL1522", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1522RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1522", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1522LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1919: { RS: { bench: "RS1919", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1919RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1919", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1919LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1919L": { RL: { bench: "RL1919", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1919RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1919", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1919LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  1920: { RS: { bench: "RS1920", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1920RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS1920", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1920LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1920L": { RL: { bench: "RL1920", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1920RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1920", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1920LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1922L": { RL: { bench: "RL1922", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1922RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL1922", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1922LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1922MS": { MS: { bench: "MS1922", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1922MS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "1922MD": { MD: { bench: "MD1922", images: ["https://www.sawo.com/wp-content/uploads/2026/02/1922MD_LATEST-NEW-SAUNA-ROOM.webp"] } },
  2020: { RS: { bench: "RS2020", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2020RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS2020", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2020LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "2020L": { RL: { bench: "RL2020", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2020RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL2020", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2020LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  2022: { RS: { bench: "RS2022", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2022RS_LATEST-NEW-SAUNA-ROOM.webp"] }, LS: { bench: "LS2022", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2022LS_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "2022L": { RL: { bench: "RL2022", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2022RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL2022", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2022LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "2022MD": { MD: { bench: "MD2022", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2022MD_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "2222L": { RL: { bench: "RL2222", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2222RL_LATEST-NEW-SAUNA-ROOM.webp"] }, LL: { bench: "LL2222", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2222LL_LATEST-NEW-SAUNA-ROOM.webp"] } },
  "2222MD": { MD: { bench: "MD2222", images: ["https://www.sawo.com/wp-content/uploads/2026/02/2222-MD_LATEST-NEW-SAUNA-ROOM.webp"] } },
};

const standardSizeData = {
  1214: { w: "1.36m", d: "1.16m", h: "2.12m", c: "1-3 People" },
  1215: { w: "1.54m", d: "1.16m", h: "2.12m", c: "1-3 People" },
  1414: { w: "1.36m", d: "1.36m", h: "2.12m", c: "1-3 People" },
  1415: { w: "1.54m", d: "1.36m", h: "2.12m", c: "1-3 People" },
  1515: { w: "1.54m", d: "1.54m", h: "2.12m", c: "1-3 People" },
  "1515L": { w: "1.54m", d: "1.54m", h: "2.12m", c: "1-3 People" },
  1419: { w: "1.85m", d: "1.36m", h: "2.12m", c: "4-6 People" },
  1420: { w: "2.04m", d: "1.36m", h: "2.12m", c: "4-6 People" },
  1519: { w: "1.85m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  "1519L": { w: "1.85m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  1520: { w: "2.04m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  "1520L": { w: "2.04m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  1522: { w: "2.23m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  "1522L": { w: "2.23m", d: "1.54m", h: "2.12m", c: "4-6 People" },
  1919: { w: "1.85m", d: "1.85m", h: "2.12m", c: "4-6 People" },
  "1919L": { w: "1.85m", d: "1.85m", h: "2.12m", c: "4-6 People" },
  1920: { w: "2.04m", d: "1.85m", h: "2.12m", c: "4-6 People" },
  "1920L": { w: "2.04m", d: "1.85m", h: "2.12m", c: "4-6 People" },
  "1922L": { w: "2.23m", d: "1.85m", h: "2.12m", c: "6+ People" },
  "1922MS": { w: "2.23m", d: "1.85m", h: "2.12m", c: "6+ People" },
  "1922MD": { w: "2.23m", d: "1.85m", h: "2.12m", c: "6+ People" },
  2020: { w: "2.04m", d: "2.04m", h: "2.12m", c: "6+ People" },
  "2020L": { w: "2.04m", d: "2.04m", h: "2.12m", c: "6+ People" },
  2022: { w: "2.23m", d: "2.04m", h: "2.12m", c: "6+ People" },
  "2022L": { w: "2.23m", d: "2.04m", h: "2.12m", c: "6+ People" },
  "2022MD": { w: "2.23m", d: "2.04m", h: "2.12m", c: "6+ People" },
  "2222L": { w: "2.23m", d: "2.23m", h: "2.12m", c: "6+ People" },
  "2222MD": { w: "2.21m", d: "2.21m", h: "2.12m", c: "6+ People" },
};

const standardBenchTypes = {
  RS1214: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1214RS.webp" },
  LS1214: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1214LS.webp" },
  RS1215: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1215RS.webp" },
  LS1215: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1215LS.webp" },
  RS1414: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1414RS.webp" },
  LS1414: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1414LS.webp" },
  RS1415: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1415RS.webp" },
  LS1415: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1415LS.webp" },
  RS1515: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1515RS.webp" },
  LS1515: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1515LS.webp" },
  RL1515: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1515RL.webp" },
  LL1515: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/03/Standard-Sauna-Room-Horizontal-Panel-1515LL.webp" },
  RS1419: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1419RS.webp" },
  LS1419: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1419LS.webp" },
  RS1420: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1420RS.webp" },
  LS1420: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1420LS.webp" },
  RS1519: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1519RS.webp" },
  LS1519: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1519LS.webp" },
  RL1519: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1519RL.webp" },
  LL1519: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1519LL.webp" },
  RS1520: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1520RS.webp" },
  LS1520: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1520LS.webp" },
  RL1520: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1520RL.webp" },
  LL1520: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1520LL.webp" },
  RS1522: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1522RS.webp" },
  LS1522: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1522LS.webp" },
  RL1522: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1522RL.webp" },
  LL1522: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1522LL.webp" },
  RS1919: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1919RS.webp" },
  LS1919: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1919LS.webp" },
  RL1919: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1919RL.webp" },
  LL1919: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1919LL.webp" },
  RS1920: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1920RS.webp" },
  LS1920: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1920LS.webp" },
  RL1920: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1920RL.webp" },
  LL1920: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1920LL.webp" },
  RL1922: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1922RL.webp" },
  LL1922: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1922LL.webp" },
  MS1922: { name: "Single Straight Bench", title: "Standard Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1922MS.webp" },
  MD1922: { name: "Double Straight Bench", title: "Standard Sauna Room", class: "double", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-1922MD.webp" },
  RS2020: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2020RS.webp" },
  LS2020: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2020LS.webp" },
  RL2020: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2020RL.webp" },
  LL2020: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2020LL.webp" },
  RS2022: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2022RS.webp" },
  LS2022: { name: "Straight Bench", title: "Standard Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2022LS.webp" },
  RL2022: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2022RL.webp" },
  LL2022: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2022LL.webp" },
  MD2022: { name: "Double Straight Bench", title: "Standard Sauna Room", class: "double", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2022MD.webp" },
  RL2222: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2222RL.webp" },
  LL2222: { name: "L-Type Bench", title: "Standard Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2222LL.webp" },
  MD2222: { name: "Double Straight Bench", title: "Standard Sauna Room", class: "double", image: "https://www.sawo.com/wp-content/uploads/2026/02/Standard-Sauna-Room-Horizontal-Panel-2222MD.webp" },
};

const standardSizeCategories = {
  small: ["1214", "1215", "1414", "1415", "1515", "1515L"],
  medium: ["1419", "1420", "1519", "1519L", "1520", "1520L", "1522", "1522L", "1919", "1919L", "1920", "1920L"],
  large: ["1922L", "1922MS", "1922MD", "2020", "2020L", "2022", "2022L", "2022MD", "2222L", "2222MD"],
};

const glassFrontImageData = {
  1414: { RS: { bench: "RS1414", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1414RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1414", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1414LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1415: { RS: { bench: "RS1415", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1415RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1415", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1415LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1419: { RS: { bench: "RS1419", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1419RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1419", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1419LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1419MS": { MS: { bench: "MS1419", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1419MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1515: { RS: { bench: "RS1515", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1515RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1515", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1515LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1519: { RS: { bench: "RS1519", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1519RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1519", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1519LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1519MS": { MS: { bench: "MS1519", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1519MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1420: { RS: { bench: "RS1420", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1420RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1420", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1420LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1420MS": { MS: { bench: "MS1420", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1420MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1520: { RS: { bench: "RS1520", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1520RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1520", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1520LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1520MS": { MS: { bench: "MS1520", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1520MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1522: { RS: { bench: "RS1522", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1522RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1522", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1522LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1522MS": { MS: { bench: "MS1522", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1522MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1919: { RS: { bench: "RS1919", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1919RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1919", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1919LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1919MS": { MS: { bench: "MS1919", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1919MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1919MRL": { MRL: { bench: "MRL1919", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1919MrL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, MIL: { bench: "MIL1919", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1919MiL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1920: { RS: { bench: "RS1920", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1920RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1920", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1920LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1920MS": { MS: { bench: "MS1920", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1920MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1920MRL": { MRL: { bench: "MRL1920", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1920MrL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, MIL: { bench: "MIL1920", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1920MiL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  1922: { RS: { bench: "RS1922", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1922RS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS1922", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1922LS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1922MS": { MS: { bench: "MS1922", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1922MS-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "1922MRL": { MRL: { bench: "MRL1922", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1922MrL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, MIL: { bench: "MIL1922", images: ["https://www.sawo.com/wp-content/uploads/2026/03/1922MiL-GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  2020: { RS: { bench: "RS2020", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2020RS_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LS: { bench: "LS2020", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2020LS_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2020MS": { MS: { bench: "MS2020", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2020MS_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2020MRL": { MRL: { bench: "MRL2020", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2020MRL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, MIL: { bench: "MIL2020", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2020MiL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2022L": { RL: { bench: "RL2022", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2022RL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LL: { bench: "LL2022", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2022LL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2022MD": { MD: { bench: "MD2022", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2022MD_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2222L": { RL: { bench: "RL2222", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2222RL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] }, LL: { bench: "LL2222", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2222LL_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
  "2222MD": { MD: { bench: "MD2222", images: ["https://www.sawo.com/wp-content/uploads/2026/03/2222MD_GLASS-FRONT-PERSPECTIVE-VIEW.webp"] } },
};

const glassFrontSizeData = {
  1414: { w: "1.36m", d: "1.37m", h: "2.12m", c: "1-3 People" },
  1415: { w: "1.54m", d: "1.37m", h: "2.12m", c: "1-3 People" },
  1419: { w: "1.85m", d: "1.37m", h: "2.12m", c: "1-3 People" },
  "1419MS": { w: "1.85m", d: "1.37m", h: "2.12m", c: "1-3 People" },
  1515: { w: "1.54m", d: "1.56m", h: "2.12m", c: "1-3 People" },
  1519: { w: "1.85m", d: "1.56m", h: "2.12m", c: "1-3 People" },
  "1519MS": { w: "1.85m", d: "1.56m", h: "2.12m", c: "1-3 People" },
  1420: { w: "2.04m", d: "1.37m", h: "2.12m", c: "4-6 People" },
  "1420MS": { w: "2.06m", d: "1.37m", h: "2.12m", c: "4-6 People" },
  1520: { w: "2.04m", d: "1.56m", h: "2.12m", c: "4-6 People" },
  "1520MS": { w: "2.06m", d: "1.56m", h: "2.12m", c: "4-6 People" },
  1522: { w: "2.23m", d: "1.56m", h: "2.12m", c: "4-6 People" },
  "1522MS": { w: "2.23m", d: "1.56m", h: "2.12m", c: "4-6 People" },
  1919: { w: "1.85m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  "1919MS": { w: "1.85m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  "1919MRL": { w: "1.85m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  1920: { w: "2.04m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  "1920MS": { w: "2.06m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  "1920MRL": { w: "2.06m", d: "1.87m", h: "2.12m", c: "4-6 People" },
  1922: { w: "2.23m", d: "1.87m", h: "2.12m", c: "6+ People" },
  "1922MS": { w: "2.23m", d: "1.85m", h: "2.12m", c: "6+ People" },
  "1922MRL": { w: "2.23m", d: "1.85m", h: "2.12m", c: "6+ People" },
  2020: { w: "2.04m", d: "2.06m", h: "2.12m", c: "6+ People" },
  "2020MS": { w: "2.06m", d: "2.06m", h: "2.12m", c: "6+ People" },
  "2020MRL": { w: "2.06m", d: "2.06m", h: "2.12m", c: "6+ People" },
  "2022L": { w: "2.23m", d: "2.06m", h: "2.12m", c: "6+ People" },
  "2022MD": { w: "2.23m", d: "2.06m", h: "2.12m", c: "6+ People" },
  "2222L": { w: "2.23m", d: "2.25m", h: "2.12m", c: "6+ People" },
  "2222MD": { w: "2.23m", d: "2.25m", h: "2.12m", c: "6+ People" },
};

const glassFrontBenchTypes = {
  RS1414: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1414RS.webp" },
  LS1414: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1414LS.webp" },
  RS1415: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1415RS.webp" },
  LS1415: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1415LS.webp" },
  RS1419: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1419RS.webp" },
  LS1419: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1419LS.webp" },
  MS1419: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1419MS.png" },
  RS1515: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1515RS.webp" },
  LS1515: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1515LS.webp" },
  RS1519: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1519RS.webp" },
  LS1519: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1519LS.webp" },
  MS1519: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1519MS.png" },
  RS1420: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1420RS.png" },
  LS1420: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1420LS.webp" },
  MS1420: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1420MS.png" },
  RS1520: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1520RS.webp" },
  LS1520: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1520LS.webp" },
  MS1520: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1520MS.png" },
  RS1522: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1522RS.webp" },
  LS1522: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1522LS.webp" },
  MS1522: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1522MS.webp" },
  RS1919: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1919RS.webp" },
  LS1919: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1919LS.webp" },
  MS1919: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1919MS.webp" },
  MRL1919: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1919MRL.webp" },
  MIL1919: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1919MLL.webp" },
  RS1920: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1920RS.webp" },
  LS1920: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1920LS.webp" },
  MS1920: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-Horizontal-Panel-1920MS.png" },
  MRL1920: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1920MRL.webp" },
  MIL1920: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1920MLL.webp" },
  RS1922: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1922RS.webp" },
  LS1922: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1922LS.webp" },
  MS1922: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-Horizontal-Panel-1922MS.png" },
  MRL1922: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1922MRL.webp" },
  MIL1922: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-1922MLL.webp" },
  RS2020: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2020RS.webp" },
  LS2020: { name: "Straight Bench", title: "Glass Front Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2020LS.webp" },
  MS2020: { name: "Single Straight Bench", title: "Glass Front Sauna Room", class: "single", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2020MS.webp" },
  MRL2020: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2020MRL.webp" },
  MIL2020: { name: "Middle L-Type Bench", title: "Glass Front Sauna Room", class: "middle-l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2020MLL.webp" },
  RL2022: { name: "L-Type Bench", title: "Glass Front Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2022RL.webp" },
  LL2022: { name: "L-Type Bench", title: "Glass Front Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2022LL.webp" },
  MD2022: { name: "Double Straight Bench", title: "Glass Front Sauna Room", class: "double", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2022MD.webp" },
  RL2222: { name: "L-Type Bench", title: "Glass Front Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2222RL.webp" },
  LL2222: { name: "L-Type Bench", title: "Glass Front Sauna Room", class: "l-type", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2222LL.webp" },
  MD2222: { name: "Double Straight Bench", title: "Glass Front Sauna Room", class: "double", image: "https://www.sawo.com/wp-content/uploads/2026/02/Glass-Front-Sauna-Room-2222MD.webp" },
};

const glassFrontSizeCategories = {
  small: ["1414", "1415", "1419", "1419MS", "1515", "1519", "1519MS"],
  medium: ["1420", "1420MS", "1520", "1520MS", "1522", "1522MS", "1919", "1919MS", "1919MRL", "1920", "1920MS", "1920MRL"],
  large: ["1922", "1922MS", "1922MRL", "2020", "2020MS", "2020MRL", "2022L", "2022MD", "2222L", "2222MD"],
};

const infraredImageData = {
  "0908-IR-D": { bench: "0908-IR-D", images: ["https://www.sawo.com/wp-content/uploads/2026/02/SR05-3433420_IR-0908MS-PERSPECTIVE-VIEW.webp"] },
  "1111-IR-D": { bench: "1111-IR-D", images: ["https://www.sawo.com/wp-content/uploads/2026/02/SR05-3303290_IR-1111RS-_PERSPECTIVE-VIEW.webp"] },
};

const infraredSizeData = {
  "0908-IR-D": { w: "0.80m", d: "0.90m", h: "2.05m", c: "1 Person" },
  "1111-IR-D": { w: "1.10m", d: "1.10m", h: "2.05m", c: "2 Person" },
};

const infraredBenchTypes = {
  "0908-IR-D": { name: "Straight Bench", title: "Infrared Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/0908MS-TOP-VIEW-with-DIMENSION.webp" },
  "1111-IR-D": { name: "Straight Bench", title: "Infrared Sauna Room", class: "straight", image: "https://www.sawo.com/wp-content/uploads/2026/02/1111RS-_TOP-VIEW-with-DIMENSION.webp" },
};

const SFW_ITEMS = [
  {
    tab: "Ventilation",
    image: "https://www.sawo.com/wp-content/uploads/2026/03/Ventilation-800x800-1.png",
    title: "Ventilation",
    paragraphs: [
      "Proper ventilation is essential for removing CO₂, pathogens and equalising the temperature inside your sauna. Most sauna kits lack this entirely.",
      "SAWO's built-in intake vent brings oxygen-rich air directly to the heater, mixing it into the rising airflow — allowing longer, more comfortable sessions without the sluggishness of CO₂ buildup.",
      "The integrated exhaust vent equalises temperatures throughout the room while actively drying your sauna after each use, extending its lifespan significantly.",
    ],
    specs: null,
  },
  {
    tab: "Lighting",
    image: "https://www.sawo.com/wp-content/uploads/2025/11/TR-LIGHT-COVER_SCENE1-copy.webp",
    title: "Lighting",
    paragraphs: [
      "The right lighting transforms a sauna session into a complete sensory experience. SAWO's integrated LED system is designed to complement the warmth of the wood and the heat of the room.",
      "Soft, low-glare positioning around the bench and ceiling creates a calm, immersive atmosphere — never harsh or clinical. Fully dimmable to suit any mood or time of day.",
      "All components are rated for the heat and humidity of a sauna environment, ensuring safe and reliable performance for years of daily use.",
    ],
    specs: null,
  },
  {
    tab: "Bench Height",
    image: "https://www.sawo.com/wp-content/uploads/2025/09/PREVENTIVE-MAINTENANCE.jpg",
    title: "Bench Height",
    paragraphs: [
      "Bench height plays a critical role in the quality of your sauna experience. Higher benches sit closer to the ceiling where temperatures are warmest, while lower benches offer a gentler, more relaxed heat.",
      "SAWO benches are crafted from premium kiln-dried timber and positioned to maximise heat exposure and comfort simultaneously. Available in straight and L-type configurations to suit any room layout.",
      "Every bench is finished to a smooth, splinter-free surface, designed for daily use without maintenance concerns.",
    ],
    specs: null,
  },
  {
    tab: "Excellent Heat",
    image: "https://www.sawo.com/wp-content/uploads/2025/10/SAWO_heater_accessories_Cozy_tank_on_th12_rnd.webp",
    title: "Excellent Heat",
    paragraphs: [
      "Even, consistent heat is what separates a great sauna from a good one. SAWO heaters are engineered to distribute warmth uniformly across the entire room — no cold corners, no hot spots.",
      "Reaching target temperatures quickly and holding them precisely, our heaters are designed for efficiency without sacrificing the deep, penetrating heat that defines the Finnish experience.",
      "Compatible with both wet and dry sauna sessions, giving you full control over the intensity and character of every session.",
    ],
    specs: null,
  },
  {
    tab: "Room Sizes",
    image: "https://www.sawo.com/wp-content/uploads/2024/10/2020ML-CD-G-SCENE.png",
    title: "Room Sizes",
    paragraphs: [
      "SAWO sauna rooms are available in three size categories, designed to fit any space — from a compact home bathroom to a dedicated wellness room.",
    ],
    specs: [
      { key: "Small Rooms",   val: "1.16m–1.54m wide", note: "/ 1–3 people" },
      { key: "Medium Rooms",  val: "1.36m–1.85m wide", note: "/ 4–6 people" },
      { key: "Large Rooms",   val: "1.85m–2.23m wide", note: "/ 6+ people" },
      { key: "Height",        val: "2.12m",             note: "(all models)" },
      { key: "Bench Types",   val: "Straight, L-Type, Double Straight, Double with Middle Door", note: null },
      { key: "Material",      val: "Cedar, Aspen or Pinaceae", note: null },
    ],
  },
  {
    tab: "Insulation",
    image: "https://www.sawo.com/wp-content/uploads/2026/03/Tower-heaters-round-scene_with-steam.jpg",
    title: "Insulation",
    paragraphs: [
      "Proper insulation is the foundation of an efficient sauna. SAWO rooms are built with high-performance insulation that retains heat inside the cabin and prevents energy loss through the walls, floor, and ceiling.",
      "This means faster heat-up times, lower running costs, and a more consistent temperature throughout your session — regardless of the ambient conditions outside.",
      "SAWO's insulation is also moisture-resistant, protecting the structural integrity of the room over years of daily use and steam exposure.",
    ],
    specs: null,
  },
];

const SFW_AUTO_DELAY   = 4000;
const SFW_RESUME_DELAY = 8000;

const SPD_SLIDES = [
  { src: "https://www.sawo.com/wp-content/uploads/2026/02/STANDARD-SAUNA-ROOM-COVER-scaled.webp",  alt: "Standard Sauna Room" },
  { src: "https://www.sawo.com/wp-content/uploads/2026/02/GLASS-FRONT-SAUNA-ROOM-V3-scaled.webp", alt: "Glass Front Sauna Room" },
  { src: "https://www.sawo.com/wp-content/uploads/2026/02/IR-1111RS-_SCENE-.webp",               alt: "IR Sauna Room" },
];

const SPD_STORY_SECTIONS = [
  {
    title: "Your Own Private Retreat",
    paragraphs: [
      "Imagine finishing a long day and stepping into your own sauna — heat rising, muscles unwinding, the world outside falling quiet. SAWO sauna rooms bring that experience home, available in sizes from compact 1–3 person rooms all the way up to spacious 6+ person suites, so there's a perfect fit for every space and every household.",
      "Whether you're looking for a solo sanctuary or a place to unwind with family and friends, our rooms are designed to make that luxury effortless and permanent — no gym membership, no booking ahead, just pure Finnish heat whenever you need it.",
    ],
  },
  {
    title: "Authentic Finnish Craftsmanship",
    paragraphs: [
      "SAWO has been building saunas in Finland for over 30 years, and every room reflects that heritage. Each sauna is available in cedar, aspen, or pinaceae — each wood bringing its own natural character, aroma, and feel to your sessions.",
      "Choose from straight bench or L-type bench configurations, with left and right-hand door options to suit your space. Every detail, from the bench layout to the panel joinery, is designed the way Finns have always done it — with simplicity, quality, and longevity in mind.",
    ],
  },
];

const SPD_FEATURE_TEXT = "Regular sauna use detoxifies naturally, improves circulation, and accelerates muscle recovery after exercise. The warmth eases stress, deepens sleep, and leaves you feeling restored — session after session. And beyond the wellness benefits, a SAWO sauna room is a lasting addition to your home that increases its value and sets it apart.";

const SPD_PERF_CARDS = [
  { label: "Cedar, Aspen or Pinaceae",    detail: "Naturally aromatic, sustainably sourced" },
  { label: "3 Size Categories",            detail: "1–3, 4–6, and 6+ person configurations" },
  { label: "Straight & L-Type Benches",   detail: "Left and right-hand door options available" },
  { label: "Finnish Made, 30+ Years",      detail: "Decades of sauna expertise in every room" },
];

const SPD_ACCORDION_ITEMS = [
  {
    title: "Product Specifications",
    specs: [
      { label: "Small Rooms",  value: "1.16m–1.54m wide", unit: "/ 1–3 people" },
      { label: "Medium Rooms", value: "1.36m–1.85m wide", unit: "/ 4–6 people" },
      { label: "Large Rooms",  value: "1.85m–2.23m wide", unit: "/ 6+ people" },
      { label: "Height",       value: "2.12m",             unit: "(all models)" },
      { label: "Bench Types",  value: "Straight, L-Type, Double Straight, Double with Middle Door", unit: null },
      { label: "Material",     value: "Cedar, Aspen or Pinaceae", unit: null },
    ],
  },
];

const SPD_SLIDE_DELAY    = 4000;
const SPD_LOADER_TIMEOUT = 6000;

const SRD_PANELS = [
  {
    pill: "Standard",
    label: "About This Room",
    title: "Standard Sauna Room",
    descriptions: [
      "The SAWO Standard Sauna Room brings the authentic Finnish sauna experience to your home. Designed with simplicity and elegance, it combines traditional craftsmanship with modern engineering.",
      "Each room is precision-built to maintain optimal heat circulation and energy efficiency, ensuring a consistent and comfortable sauna session every time.",
    ],
    features: [
      "Easy assembly with pre-built wall panels",
      "Premium heat-treated wood construction",
      "Tempered glass door with magnetic seal",
      "Available in all sizes and with multiple wood finishes",
    ],
    image: "https://www.sawo.com/wp-content/uploads/2025/11/2560x1920.webp",
    imageAlt: "Standard Sauna Room",
  },
  {
    pill: "Glass Front",
    label: "About This Room",
    title: "Glass Front Sauna Room",
    descriptions: [
      "The SAWO Glass Front Sauna Room combines contemporary design with traditional sauna benefits. Featuring a stunning full glass front panel, this modern sauna creates an open, airy atmosphere while maintaining exceptional heat retention.",
      "Perfect for those who appreciate both aesthetics and functionality, the glass front design brings natural light into your sauna space and creates a luxurious spa-like ambiance.",
    ],
    features: [
      "Full glass front panel for modern aesthetic",
      "Triple-layered tempered safety glass",
      "Enhanced heat insulation technology",
      "Available in all sizes and wood options",
    ],
    image: "https://www.sawo.com/wp-content/uploads/2026/02/1420-Glass-Front-Sauna-Room-scaled-1.webp",
    imageAlt: "Glass Front Sauna Room",
  },
  {
    pill: "Infrared",
    label: "About This Room",
    title: "Infrared Sauna Room",
    descriptions: [
      "SAWO's standard infrared sauna rooms come in two sizes, either for a single person or for two people. The far-infrared panels do not heat the room as much as a traditional sauna does, so the majority of the heat produced is heating the body directly.",
      "Featuring fiber-coated far infrared panels (170W per panel), these energy-efficient saunas offer 1-person (1200W) or 2-person (1400W) configurations with premium cedar construction and plug-and-play 230V installation.",
    ],
    features: [
      "Fiber-coated far infrared panels (170W/panel)",
      "230V plug-and-play installation",
      "Digital control for temperature, time, lights & fan",
      "Modern LED lights (12W) & pre-installed exhaust fan (18W)",
      "Adjustable base support & session time: 1–60 minutes",
      "Premium cedar construction",
    ],
    image: "https://www.sawo.com/wp-content/uploads/2026/02/IR-1111RS-_SCENE-.webp",
    imageAlt: "Infrared Sauna Room",
  },
];

const SRD_AUTO_DELAY = 8000;

const S3T_VIEWER_URL  = "https://www.sawo.com/3d-viewer/";
const S3T_MODEL_LABEL = "1414RS · Glass Front";

const MATS_ITEMS = [
  {
    name: "Cedar",
    image: "https://www.sawo.com/wp-content/uploads/2025/11/Cedar-Panels.webp",
    alt: "Cedar wood",
    description: "Rich, aromatic wood with natural resistance to moisture. Known for its warm reddish-brown tones and distinctive scent.",
    traits: ["Aromatic", "Moisture-Resistant", "Warm Tones"],
  },
  {
    name: "Aspen",
    image: "https://www.sawo.com/wp-content/uploads/2025/11/Aspen-Panels.webp",
    alt: "Aspen wood",
    description: "Light, hypoallergenic wood with a smooth finish. Cool to the touch and perfect for those with sensitivities.",
    traits: ["Hypoallergenic", "Cool Touch", "Light Grain"],
  },
  {
    name: "Pinaceae",
    image: "https://www.sawo.com/wp-content/uploads/2026/02/HEMLOCK-PANELS.webp",
    alt: "Pinaceae wood",
    description: "Traditional Nordic sauna wood with a clean, natural grain. Excellent heat properties and timeless aesthetic appeal.",
    traits: ["Traditional", "Heat-Efficient", "Natural Grain"],
  },
];

const HASH_MAP = {
  "standard-sauna-room": "standard",
  "glass-front-sauna-room": "glassfront",
  "infrared-sauna-room": "infrared",
};

const ROOM_CONFIGS = {
  standard: {
    label: "Standard Sauna Room",
    desc: "SAWO Classic Sauna Rooms offer a timeless sauna experience with high-quality Nordic wood and practical bench layouts.",
    imageData: standardImageData,
    sizeData: standardSizeData,
    benchTypes: standardBenchTypes,
    sizeCategories: standardSizeCategories,
    hasDoorFilter: true,
    isFlat: false,
    suffixRegex: /L$|MS$|MD$/,
    sideOrder: ["RS", "LS", "RL", "LL", "MS", "MD"],
    sizeOptions: [
      { value: "1214", label: "1214 (RS/LS)" }, { value: "1215", label: "1215 (RS/LS)" },
      { value: "1414", label: "1414 (RS/LS)" }, { value: "1415", label: "1415 (RS/LS)" },
      { value: "1419", label: "1419 (RS/LS)" }, { value: "1420", label: "1420 (RS/LS)" },
      { value: "1515", label: "1515 (RS/LS)" }, { value: "1515L", label: "1515 (RL/LL)" },
      { value: "1519", label: "1519 (RS/LS)" }, { value: "1519L", label: "1519 (RL/LL)" },
      { value: "1520", label: "1520 (RS/LS)" }, { value: "1520L", label: "1520 (RL/LL)" },
      { value: "1522", label: "1522 (RS/LS)" }, { value: "1522L", label: "1522 (RL/LL)" },
      { value: "1919", label: "1919 (RS/LS)" }, { value: "1919L", label: "1919 (RL/LL)" },
      { value: "1920", label: "1920 (RS/LS)" }, { value: "1920L", label: "1920 (RL/LL)" },
      { value: "1922L", label: "1922 (RL/LL)" }, { value: "1922MS", label: "1922 (MS)" },
      { value: "1922MD", label: "1922 (MD)" }, { value: "2020", label: "2020 (RS/LS)" },
      { value: "2020L", label: "2020 (RL/LL)" }, { value: "2022", label: "2022 (RS/LS)" },
      { value: "2022MD", label: "2022 (MD)" }, { value: "2022L", label: "2022 (RL/LL)" },
      { value: "2222L", label: "2222 (RL/LL)" }, { value: "2222MD", label: "2222 (MD)" },
    ],
    doorOptions: [
      { value: "RS", label: "Right Side" }, { value: "LS", label: "Left Side" },
      { value: "MS", label: "Middle" }, { value: "RL", label: "Right Side (L-Type)" },
      { value: "LL", label: "Left Side (L-Type)" }, { value: "MD", label: "Middle (Double)" },
    ],
    woodOptions: ["Cedar", "Aspen", "Pinaceae"],
    woodEnabled: [true, false, false],
    bestSellers: null,
  },
  glassfront: {
    label: "Glass Front Sauna Room",
    desc: "SAWO Glass Front Sauna Rooms offer a modern sauna experience with durable glass to overlook stunning views without compromising on practicality.",
    imageData: glassFrontImageData,
    sizeData: glassFrontSizeData,
    benchTypes: glassFrontBenchTypes,
    sizeCategories: glassFrontSizeCategories,
    hasDoorFilter: true,
    isFlat: false,
    suffixRegex: /MS$|MRL$|MIL$|MD$|RL$|LL$|LS$|L$/,
    sideOrder: ["RS", "LS", "MS", "MRL", "MIL", "MD", "RL", "LL"],
    sizeOptions: [
      { value: "1414", label: "1414 (RS/LS)" }, { value: "1415", label: "1415 (RS/LS)" },
      { value: "1419", label: "1419 (RS/LS)" }, { value: "1419MS", label: "1419 (MS)" },
      { value: "1515", label: "1515 (RS/LS)" }, { value: "1519", label: "1519 (RS/LS)" },
      { value: "1519MS", label: "1519 (MS)" }, { value: "1420", label: "1420 (RS/LS)" },
      { value: "1420MS", label: "1420 (MS)" }, { value: "1520", label: "1520 (RS/LS)" },
      { value: "1520MS", label: "1520 (MS)" }, { value: "1522", label: "1522 (RS/LS)" },
      { value: "1522MS", label: "1522 (MS)" }, { value: "1919", label: "1919 (RS/LS)" },
      { value: "1919MS", label: "1919 (MS)" }, { value: "1919MRL", label: "1919 (MRL/MIL)" },
      { value: "1920", label: "1920 (RS/LS)" }, { value: "1920MS", label: "1920 (MS)" },
      { value: "1920MRL", label: "1920 (MRL/MIL)" }, { value: "1922", label: "1922 (RS/LS)" },
      { value: "1922MS", label: "1922 (MS)" }, { value: "1922MRL", label: "1922 (MRL/MIL)" },
      { value: "2020", label: "2020 (RS/LS)" }, { value: "2020MS", label: "2020 (MS)" },
      { value: "2020MRL", label: "2020 (MRL/MIL)" }, { value: "2022L", label: "2022 (RL/LL)" },
      { value: "2022MD", label: "2022 (MD)" }, { value: "2222L", label: "2222 (RL/LL)" },
      { value: "2222MD", label: "2222 (MD)" },
    ],
    doorOptions: [
      { value: "RS", label: "Right Side" }, { value: "LS", label: "Left Side" },
      { value: "MS", label: "Middle" }, { value: "MRL", label: "Middle Right (L-Type)" },
      { value: "MIL", label: "Middle Left (L-Type)" }, { value: "MD", label: "Middle (Double)" },
      { value: "RL", label: "Right Side (L-Type)" }, { value: "LL", label: "Left Side (L-Type)" },
    ],
    woodOptions: ["Cedar", "Aspen", "Pinaceae"],
    woodEnabled: [true, false, false],
    bestSellers: new Set(["1414"]),
  },
  infrared: {
    label: "Infrared Sauna Room",
    desc: "SAWO Infrared Sauna Rooms provide gentle, therapeutic heat using advanced infrared technology for a relaxing and rejuvenating experience.",
    imageData: infraredImageData,
    sizeData: infraredSizeData,
    benchTypes: infraredBenchTypes,
    sizeCategories: null,
    hasDoorFilter: false,
    isFlat: true,
    suffixRegex: null,
    sideOrder: [],
    sizeOptions: [
      { value: "0908-IR-D", label: "0908-IR-D (1 Person)" },
      { value: "1111-IR-D", label: "1111-IR-D (2 Person)" },
    ],
    doorOptions: [],
    woodOptions: ["Cedar", "Hemlock"],
    woodEnabled: [true, false],
    bestSellers: null,
  },
};

export {
  standardImageData, standardSizeData, standardBenchTypes, standardSizeCategories,
  glassFrontImageData, glassFrontSizeData, glassFrontBenchTypes, glassFrontSizeCategories,
  infraredImageData, infraredSizeData, infraredBenchTypes,
  ROOM_CONFIGS, HASH_MAP,
  SFW_ITEMS, SFW_AUTO_DELAY, SFW_RESUME_DELAY,
  SPD_SLIDES, SPD_STORY_SECTIONS, SPD_FEATURE_TEXT, SPD_PERF_CARDS,
  SPD_ACCORDION_ITEMS, SPD_SLIDE_DELAY, SPD_LOADER_TIMEOUT,
  SRD_PANELS, SRD_AUTO_DELAY,
  S3T_VIEWER_URL, S3T_MODEL_LABEL,
  MATS_ITEMS,
};